// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace ShortLegStudio
{
	public static class ArrayExtensions
	{
		public static T ChooseOne<T>(this T[] source) {
			var index = Randomly.Range (0, source.Length);
			return source[index];
		}

		public static T ChooseOne<T>(this IList<T> source) {
			var index = Randomly.Range (0, source.Count);
			return source [index];
		}


		/// UI Extensions TODO: Move them around

		public static void SelectOption(this UnityEngine.UI.Dropdown dropdown, string value) {
			for (var i = 0; i < dropdown.options.Count; i++) {
				if (dropdown.options [i].text == value) {
					dropdown.value = i;
				}
			}
		}
	}
}

