// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace ShortLegStudio
{
	public static class CollectionExtensions
	{
		public static T ChooseOne<T>(this T[] source) {
			var index = Randomly.Range (0, source.Length);
			return source[index];
		}

		public static T ChooseOne<T>(this IList<T> source) {
			if (source == null || source.Count == 0)
				throw new ArgumentException ("Cannot choose from an empty list");
			var index = Randomly.Range (0, source.Count);
			return source [index];
		}

		public static void Add<T>(this IList<T> source, IEnumerable<T> items) {
			foreach (var i in items) {
				source.Add (i);
			}
		}

		/// UI Extensions TODO: Move them around

		public static void SelectOption(this UnityEngine.UI.Dropdown dropdown, string value) {
			for (var i = 0; i < dropdown.options.Count; i++) {
				if (dropdown.options [i].text == value) {
					dropdown.value = i;
				}
			}
		}
	}
}

